### ISSUE TITLE
Are you able to get this repo running?

### ISSUE THREAD

**Issue by xiaofeng-fan** [sff1019/meta_irl#1]
Hi, I ran into difficulty when trying the original repo. Just want to check if you are able to get it working? Thanks.

**Comment by sff1019** [comment]
Hi there! Yes, I was able to run it after some time. Not sure if this repo is my latest commit, but happy to help you out on my free time!

**Comment by xiaofeng-fan** [comment]
Wow, that's cool. I see you modified the environment configuration file. I think I was struggling at the dependencies. Let me give it one more try!

Thanks for the fast reply. Feels a relief to hear that you are able to run it, as I need to run some customized experiments for course project.

**Comment by sff1019** [comment]
Dependencies did take some time for me as well. One thing that worked for me was to install dependencies one at a time.
Good luck on your project!

**Comment by xiaofeng-fan** [comment]
Thanks. May I know which tensorflow version are you using? In the `environment.yml` it is `1.0.1`, but I saw you added `import tensorflow.compat.v1 as tf
` in the script.

**Comment by xiaofeng-fan** [comment]
Alright. I installed tf_gpu=2.0 and replaced every line of `import tensorflow as tf` in `rllab` with `import tensorflow.compat.v1 as tf`. I am able to get the training code running now! Hopefully no more issues await :) 
Thanks!

**Comment by sff1019** [comment]
Great!
